apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: iris-log-hpa
  labels:
    app: iris-log
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: iris-log-deployment
  minReplicas: 1
  maxReplicas: 3  # Kubernetes auto scaling with max_pods = 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
